on:
  push:
    branches:
      - main
jobs:
  private-public-sync:
    runs-on: ubuntu-latest
    name: Private to public repo sync
    if: endsWith(github.event.repository.name, 'yus-private')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          git remote add public 'https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git'
          git pull public main --rebase --allow-unrelated-histories
          git commit -am "Merged public commits into private"
          git push --ff-only --dry-run
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-private.git"
          source_branch: "main"
          destination_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git"
          destination_branch: "main"
