on:
  push:
    branches:
      - main

jobs:
  private-public-sync:
    runs-on: ubuntu-latest
    name: Private to public repo sync
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.email "yusinto@gmail.com"
          git config --global user.name "Yus Ng"
          git remote add public https://${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git
          git push public main