on:
  push:
    branches:
      - main

jobs:
  private-public-sync:
    runs-on: ubuntu-latest
    name: Private to public repo sync
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-private.git"
          source_branch: "main"
          destination_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git"
          destination_branch: "main"
