on:
  push:
    branches:
      - main
jobs:
  private-public-sync:
    runs-on: ubuntu-latest
    name: Private to public repo sync
    if: endsWith(github.event.repository.name, 'yus-private')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all refs instead of just the current one
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          git config --global user.email "yusinto@gmail.com"
          git config --global user.name "Yus Ngadiman"
          git remote add public 'https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git'
          git fetch public
          
          if git pull public main --rebase; then
            echo "Successfully merged public to private."
            git pull --rebase && git push
            echo "Successfully pushed to private."
          else
            echo "Conflict detected. TODO: Using the GH cli, create a PR containing the conflicts to be resolved in private repo."
            exit 1
          fi
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-private.git"
          source_branch: "main"
          destination_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git"
          destination_branch: "main"
