on:
  push:
    branches:
      - main

jobs:
  get-secret:
    runs-on: ubuntu-latest
    outputs:
      privateRepoName: ${{ steps.privateRepoName.outputs.defined }}
    steps:
      - id: privateRepoName
        env:
          PRIVATE_REPO_NAME: ${{ secrets.PRIVATE_REPO_NAME }}
        if: "${{ env.PRIVATE_REPO_NAME != '' }}"
        run: echo "::set-output name=defined::true"

  private-public-sync:
    runs-on: ubuntu-latest
    needs: [ get-secret ]
    if: github.event.repository.name == needs.get-secret.outputs.privateRepoName
    name: Private to public repo sync
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.PRIVATE_REPO_NAME }}.git"
          source_branch: "main"
          destination_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git"
          destination_branch: "main"
