on:
  push:
    branches:
      - main
jobs:
  private-public-sync:
    runs-on: ubuntu-latest
    name: Private to public repo sync
    if: endsWith(github.event.repository.name, 'yus-private')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all refs instead of just the single current one
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          git remote add public 'https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git'
          git diff --quiet --exit-code origin/main public/main -- || HAS_DIFF=1
          
          if [[ $HAS_DIFF == 1 ]]; then
            echo "Found differences between public and private. Will merge public changes into private then push from private to public."
            git config --global user.email "yusinto@gmail.com"
            git config --global user.name "Yus Ngadiman"
            git pull public main --rebase
            git commit -am "Merged public commits into private"
            git push
          else
            echo "No differences found between public and private so not pulling from public to private. Will proceed to push private to public."
          fi

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-private.git"
          source_branch: "main"
          destination_repo: "https://yusinto:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/yus-public.git"
          destination_branch: "main"
